#!/usr/bin/env python3
"""
Curate spell full_text generated by Ollama:
- Fix line-break word doubling (san sanctify -> sanctify)
- Fix literal \\n artifacts
- Join model line-wrapping (newline -> space)
- Strip ANSI escapes
- NO content changes
"""
import json, re, sys
from typing import Optional

def strip_ansi(s: str) -> str:
    s = re.sub(r'\x1b\[[0-9;]*[a-zA-Z]', '', s)
    s = re.sub(r'\x1b\][0-9;]*[^\x1b]*\x1b\\\\', '', s)
    return s

def fix_literal_backslash_n(s: str) -> str:
    return s.replace('\\n', '\n')

def fix_linebreak_word_doubling(s: str) -> str:
    """Fix 'pre\nprefixrest' -> 'prefixrest' and 'word\nword' -> 'word'"""
    return re.sub(r'(\w+)\n\1(\w*)', r'\1\2', s)

def clean_whitespace(s: str) -> str:
    s = s.replace('\r\n', '\n').replace('\r', '\n')
    s = re.sub(r'[ \t]+', ' ', s)
    s = s.strip()
    return s

def ensure_ends_with_period(s: str) -> str:
    s = s.rstrip()
    if s and not s.endswith('.') and not s.endswith('!') and not s.endswith('?'):
        s += '.'
    return s

def curate(input_path: str, output_path: Optional[str] = None):
    if output_path is None:
        output_path = input_path.replace('.json', '_curated.json')

    data = json.load(open(input_path))
    report = []
    for entry in data:
        ft = entry['full_text']
        slug = entry['slug']
        issues = []
        orig_len = len(ft)

        # Fix literal \n first (must be before newline-dependent steps)
        fixed = fix_literal_backslash_n(ft)
        if fixed != ft:
            issues.append('literal-backslash-n')
        ft = fixed

        # Fix line-break word doubling
        fixed = fix_linebreak_word_doubling(ft)
        if fixed != ft:
            issues.append('word-doubling')
        ft = fixed

        # Replace newlines with spaces (model just line-wrapped)
        had_newlines = '\n' in ft
        ft = ft.replace('\n', ' ')
        if had_newlines:
            issues.append('newlines-to-space')

        # Clean whitespace
        fixed = clean_whitespace(ft)
        if fixed != ft:
            issues.append('whitespace')
        ft = fixed

        # Ensure it ends with a period
        fixed = ensure_ends_with_period(ft)
        if fixed != ft:
            issues.append('trailing-period')
        ft = fixed

        entry['full_text'] = ft
        new_len = len(ft)
        report.append(f'  [{slug}] {orig_len} -> {new_len} chars | {", ".join(issues) if issues else "clean"}')

    json.dump(data, open(output_path, 'w'), indent=2, ensure_ascii=False)
    print(f'Wrote {len(data)} curated entries to {output_path}')
    print()
    print('\n'.join(report))

if __name__ == '__main__':
    args = sys.argv[1:]
    if not args:
        print('Usage: curate-fulltext.py <input.json> [output.json]')
        sys.exit(1)
    curate(args[0], args[1] if len(args) > 1 else None)
