/**
 * Divination system registry — single source of truth for all systems.
 *
 * Adding a new system:
 *   1. Add an entry to DIVINATION_SYSTEMS with id, label, icon, route, description
 *   2. If it needs custom UI, create a page component at src/client/pages/
 *   3. Otherwise it uses GenericDivinationPage automatically
 */

export type DivinationSystemMode =
  | "generic_llm"
  | "describe"
  | "tarot"
  | "rune"
  | "numerology"
  | "astro_watch"
  | "astro_natal"
  | "astro_deep"
  | "manifestation_llm"
  | "kabbalah"
  | "card-draw";

export interface DivinationSystemDef {
  id: string;
  label: string;
  icon: string;
  route: string;
  category: string;
  mode: DivinationSystemMode;
  description: string;
  tradition?: string;
  /** Uses shared GenericDivinationPage if true, needs custom page if false */
  generic: boolean;
}

export const DIVINATION_SYSTEMS: DivinationSystemDef[] = [
  // === Cartomancy ===
  {
    id: "tarot",
    label: "Tarot",
    icon: "Sparkles",
    route: "/consult/tarot",
    category: "Cartomancy",
    mode: "generic_llm",
    description: "35 decks across RWS, Thoth, and Marseille traditions — full traditional spreads",
    tradition: "Rider-Waite / Thoth / Marseille",
    generic: false,
  },
  {
    id: "lenormand",
    label: "Lenormand",
    icon: "Sparkles",
    route: "/consult/lenormand",
    category: "Cartomancy",
    mode: "card-draw",
    description: "36-card Petit Lenormand — Grand Tableau, card pairs, full authentic meanings based on European tradition",
    tradition: "French cartomancy",
    generic: false,
  },
  {
    id: "playing_cards",
    label: "Playing Cards",
    icon: "Sun",
    route: "/consult/playing-cards",
    category: "Cartomancy",
    mode: "card-draw",
    description: "52-card standard deck cartomancy — hearts, spades, clubs, diamonds with full traditional meanings, 5 spreads, and cartomancy history",
    tradition: "European fortune-telling / English cartomancy",
    generic: false,
  },
  {
    id: "oracle_deck",
    label: "Oracle Cards",
    icon: "Sparkles",
    route: "/consult/oracle-cards",
    category: "Cartomancy",
    mode: "generic_llm",
    description: "Modern oracle deck message for your question",
    tradition: "Contemporary",
    generic: true,
  },
  {
    id: "kipper",
    label: "Kipper Cards",
    icon: "Sparkles",
    route: "/consult/kipper",
    category: "Cartomancy",
    mode: "generic_llm",
    description: "19th-century Bavarian situational cards",
    tradition: "German Kipper",
    generic: true,
  },
  {
    id: "mahjong_oracle",
    label: "Mahjong Oracle",
    icon: "Dice4",
    route: "/consult/mahjong",
    category: "Cartomancy",
    mode: "generic_llm",
    description: "Tile draw for luck and obstacle reading",
    tradition: "Chinese folk",
    generic: true,
  },

  // === Cleromancy & Sortilege ===
  {
    id: "rune",
    label: "Elder Futhark Runes",
    icon: "Scroll",
    route: "/consult/runes",
    category: "Cleromancy & Sortilege",
    mode: "rune",
    description: "Norse rune divination — Odin's Rune, Three Norns, Five-Rune Cross, and Free Cast with full merkstave analysis",
    tradition: "Germanic",
    generic: false,
  },
  {
    id: "iching",
    label: "I Ching",
    icon: "Shuffle",
    route: "/consult/iching",
    category: "Cleromancy & Sortilege",
    mode: "generic_llm",
    description: "Three-coin casting with full hexagram data, changing lines, and secondary hexagram transformation",
    tradition: "Chinese Zhou Yi",
    generic: false,
  },
  {
    id: "ogham",
    label: "Ogham Staves",
    icon: "Scroll",
    route: "/consult/ogham",
    category: "Cleromancy & Sortilege",
    mode: "generic_llm",
    description: "Celtic tree alphabet cast — ancient Irish divination",
    tradition: "Irish-Gaelic",
    generic: true,
  },
  {
    id: "bone_throw",
    label: "Bone Reading",
    icon: "Mountain",
    route: "/consult/bone-reading",
    category: "Cleromancy & Sortilege",
    mode: "generic_llm",
    description: "Hoodoo-style bone cast and curio throw interpretation",
    tradition: "African diaspora",
    generic: true,
  },
  {
    id: "dice_oracle",
    label: "Dice Oracle",
    icon: "Dice4",
    route: "/consult/dice",
    category: "Cleromancy & Sortilege",
    mode: "generic_llm",
    description: "Pythagorean or planetary dice throw for guidance",
    tradition: "Classical sortilege",
    generic: true,
  },
  {
    id: "domino",
    label: "Domino Reading",
    icon: "Dice4",
    route: "/consult/domino",
    category: "Cleromancy & Sortilege",
    mode: "generic_llm",
    description: "Domino draw for near-term fate and insight",
    tradition: "Caribbean folk",
    generic: true,
  },
  {
    id: "lots_bibliomancy",
    label: "Sacred Lots",
    icon: "BookOpen",
    route: "/consult/sacred-lots",
    category: "Cleromancy & Sortilege",
    mode: "generic_llm",
    description: "Random verse or lot selection from sacred texts",
    tradition: "Ancient Mediterranean",
    generic: true,
  },

  // === Scrying & Vision ===
  {
    id: "crystal",
    label: "Crystal Scrying",
    icon: "Eye",
    route: "/consult/crystal-scrying",
    category: "Scrying & Vision",
    mode: "generic_llm",
    description: "Describe visions seen within the crystal sphere",
    tradition: "John Dee lineage",
    generic: true,
  },
  {
    id: "mirror",
    label: "Mirror Scrying",
    icon: "Eye",
    route: "/consult/mirror-scrying",
    category: "Scrying & Vision",
    mode: "generic_llm",
    description: "Black mirror or still water surface visions",
    tradition: "Renaissance",
    generic: true,
  },
  {
    id: "water_bowl",
    label: "Water Scrying",
    icon: "Droplets",
    route: "/consult/water-scrying",
    category: "Scrying & Vision",
    mode: "generic_llm",
    description: "Hydromancy — patterns on the water surface",
    tradition: "Universal",
    generic: true,
  },
  {
    id: "fire_gazing",
    label: "Fire Gazing",
    icon: "Flame",
    route: "/consult/fire-gazing",
    category: "Scrying & Vision",
    mode: "generic_llm",
    description: "Pyromancy — flame and candle wax interpretation",
    tradition: "Hearth magic",
    generic: true,
  },
  {
    id: "smoke",
    label: "Smoke Reading",
    icon: "Wind",
    route: "/consult/smoke-reading",
    category: "Scrying & Vision",
    mode: "generic_llm",
    description: "Capnomancy — incense smoke shape divination",
    tradition: "Temple divination",
    generic: true,
  },
  {
    id: "cloud",
    label: "Cloud Reading",
    icon: "Cloud",
    route: "/consult/cloud-reading",
    category: "Scrying & Vision",
    mode: "generic_llm",
    description: "Nephomancy — sky omens from cloud formations",
    tradition: "Weather magic",
    generic: true,
  },

  // === Physiognomy & Body ===
  {
    id: "palm",
    label: "Palm Reading",
    icon: "Hand",
    route: "/consult/palm-reading",
    category: "Physiognomy & Body",
    mode: "describe",
    description: "Chiromancy — read your life, heart, head, and fate lines",
    tradition: "Western palmistry",
    generic: true,
  },
  {
    id: "face",
    label: "Face Reading",
    icon: "Eye",
    route: "/consult/face-reading",
    category: "Physiognomy & Body",
    mode: "describe",
    description: "Physiognomy & Chinese Mian Xiang from facial features",
    tradition: "East-West blend",
    generic: true,
  },
  {
    id: "phrenology",
    label: "Phrenology Map",
    icon: "Brain",
    route: "/consult/phrenology",
    category: "Physiognomy & Body",
    mode: "describe",
    description: "Historical skull mount reading (curio — entertainment only)",
    tradition: "19th-century European",
    generic: true,
  },
  {
    id: "iris",
    label: "Iridology",
    icon: "Eye",
    route: "/consult/iridology",
    category: "Physiognomy & Body",
    mode: "describe",
    description: "Iris pattern folklore reading — not medical",
    tradition: "Folk iridology",
    generic: true,
  },
  {
    id: "foot",
    label: "Foot Reading",
    icon: "Footprints",
    route: "/consult/foot-reading",
    category: "Physiognomy & Body",
    mode: "describe",
    description: "Reflexology-style symbolic reading of foot features",
    tradition: "Asian-European folk",
    generic: true,
  },

  // === Tasseography & Food ===
  {
    id: "coffee",
    label: "Coffee Cup Reading",
    icon: "Coffee",
    route: "/consult/coffee-cup",
    category: "Tasseography & Food",
    mode: "describe",
    description: "Turkish/Greek tasseography — patterns in coffee grounds",
    tradition: "Ottoman-Greek",
    generic: true,
  },
  {
    id: "tea",
    label: "Tea Leaf Reading",
    icon: "Coffee",
    route: "/consult/tea-leaves",
    category: "Tasseography & Food",
    mode: "describe",
    description: "British tasseomancy — symbols in tea leaf patterns",
    tradition: "Victorian",
    generic: true,
  },
  {
    id: "wine_lees",
    label: "Wine Lees Reading",
    icon: "Wine",
    route: "/consult/wine-lees",
    category: "Tasseography & Food",
    mode: "describe",
    description: "Oinomancy — sediment patterns in wine",
    tradition: "Classical",
    generic: true,
  },
  {
    id: "egg",
    label: "Egg Cleanse Reading",
    icon: "Egg",
    route: "/consult/egg-cleanse",
    category: "Tasseography & Food",
    mode: "describe",
    description: "Curandero egg limpia result pattern interpretation",
    tradition: "Mexican folk",
    generic: true,
  },

  // === Numerology & Onomancy ===
  {
    id: "numerology",
    label: "Numerology Profile",
    icon: "Calculator",
    route: "/consult/numerology",
    category: "Numerology & Onomancy",
    mode: "numerology",
    description: "Life path, expression, soul urge from name and birth date",
    tradition: "Pythagorean-Chaldean",
    generic: true,
  },
  {
    id: "nameology",
    label: "Name Analysis",
    icon: "Calculator",
    route: "/consult/name-analysis",
    category: "Numerology & Onomancy",
    mode: "generic_llm",
    description: "Classical onomancy — the hidden power of names",
    tradition: "European onomancy",
    generic: true,
  },
  {
    id: "angel_numbers",
    label: "Angel Numbers",
    icon: "Star",
    route: "/consult/angel-numbers",
    category: "Numerology & Onomancy",
    mode: "generic_llm",
    description: "Repeating number synchronicity readings and meanings",
    tradition: "New Age numerology",
    generic: true,
  },

  // === Bibliomancy & Sacred Text ===
  {
    id: "bibliomancy",
    label: "Bibliomancy",
    icon: "Book",
    route: "/consult/bibliomancy",
    category: "Bibliomancy & Sacred Text",
    mode: "generic_llm",
    description: "Random sacred page or verse as divine guidance",
    tradition: "Universal",
    generic: true,
  },
  {
    id: "quran_lots",
    label: "Quranic Istikhara",
    icon: "Book",
    route: "/consult/istikhara",
    category: "Bibliomancy & Sacred Text",
    mode: "generic_llm",
    description: "Islamic guidance lot tradition (curio — educational)",
    tradition: "Islamic",
    generic: true,
  },
  {
    id: "torah_lots",
    label: "Torah Lots",
    icon: "Book",
    route: "/consult/torah-lots",
    category: "Bibliomancy & Sacred Text",
    mode: "generic_llm",
    description: "Jewish sortes biblicae — random Torah passage",
    tradition: "Jewish",
    generic: true,
  },
  {
    id: "poem_oracle",
    label: "Poem Oracle",
    icon: "Feather",
    route: "/consult/poem-oracle",
    category: "Bibliomancy & Sacred Text",
    mode: "generic_llm",
    description: "Random poetry line as oracle and inspiration",
    tradition: "Literary divination",
    generic: true,
  },

  // === Oneiromancy & Trance ===
  {
    id: "dream",
    label: "Dream Interpretation",
    icon: "Moon",
    route: "/consult/dreams",
    category: "Oneiromancy & Trance",
    mode: "generic_llm",
    description: "Oneirocritica — decode symbols from your dreams",
    tradition: "Artemidorus / Jungian",
    generic: true,
  },
  {
    id: "hypnogogic",
    label: "Hypnagogic Vision",
    icon: "Moon",
    route: "/consult/hypnagogic",
    category: "Oneiromancy & Trance",
    mode: "generic_llm",
    description: "Threshold state imagery interpretation",
    tradition: "Shamanic trance",
    generic: true,
  },
  {
    id: "automatic_writing",
    label: "Automatic Writing",
    icon: "Feather",
    route: "/consult/automatic-writing",
    category: "Oneiromancy & Trance",
    mode: "describe",
    description: "Interpret flowing text received through automatic writing",
    tradition: "Spiritist",
    generic: true,
  },

  // === Natural Omens ===
  {
    id: "augury",
    label: "Bird Augury",
    icon: "Bird",
    route: "/consult/augury",
    category: "Natural Omens",
    mode: "generic_llm",
    description: "Roman-style bird flight and behavior omen reading",
    tradition: "Roman augury",
    generic: true,
  },
  {
    id: "animal_omen",
    label: "Animal Omen",
    icon: "Bird",
    route: "/consult/animal-omen",
    category: "Natural Omens",
    mode: "generic_llm",
    description: "Animal crossing your path as a spiritual sign",
    tradition: "Shamanic",
    generic: true,
  },
  {
    id: "weather_omen",
    label: "Weather Omen",
    icon: "Cloud",
    route: "/consult/weather-omen",
    category: "Natural Omens",
    mode: "generic_llm",
    description: "Storm, wind, and lightning as divine message",
    tradition: "Folk meteoromancy",
    generic: true,
  },

  // === Spirit & Mediumship ===
  {
    id: "mediumship",
    label: "Spirit Message",
    icon: "Sparkles",
    route: "/consult/mediumship",
    category: "Spirit & Mediumship",
    mode: "generic_llm",
    description: "Channeled guidance style reading (curio — entertainment)",
    tradition: "Spiritualist",
    generic: true,
  },
  {
    id: "ancestor",
    label: "Ancestor Oracle",
    icon: "Users",
    route: "/consult/ancestor",
    category: "Spirit & Mediumship",
    mode: "generic_llm",
    description: "Honoring the dead and seeking ancestral counsel",
    tradition: "African diaspora / folk",
    generic: true,
  },
  {
    id: "pendulum",
    label: "Pendulum / Radiesthesia",
    icon: "Globe",
    route: "/consult/pendulum",
    category: "Spirit & Mediumship",
    mode: "describe",
    description: "Describe your observed yes/no pendulum swing patterns",
    tradition: "European dowsing",
    generic: true,
  },

  // === Ceremonial Oracle ===
  {
    id: "geomancy",
    label: "Geomancy",
    icon: "Mountain",
    route: "/consult/geomancy",
    category: "Ceremonial Oracle",
    mode: "generic_llm",
    description: "Sixteen tetragrams from dot figures — medieval earth divination",
    tradition: "Medieval European",
    generic: true,
  },
  {
    id: "ifá",
    label: "Ifá / Odu Oracle",
    icon: "Scroll",
    route: "/consult/ifa",
    category: "Ceremonial Oracle",
    mode: "generic_llm",
    description: "Yoruba Odu Ifá wisdom structure (curio — educational)",
    tradition: "Yoruba-Ifá",
    generic: true,
  },
  {
    id: "ifa_kikongo",
    label: "Kikongo Cosmogram",
    icon: "Globe",
    route: "/consult/kikongo",
    category: "Ceremonial Oracle",
    mode: "generic_llm",
    description: "Bakongo sign cycle reading and interpretation",
    tradition: "Kongo",
    generic: true,
  },
  {
    id: "enochian_call",
    label: "Enochian Tablet Draw",
    icon: "Scroll",
    route: "/consult/enochian",
    category: "Ceremonial Oracle",
    mode: "generic_llm",
    description: "John Dee's angelic watchtower letter draw",
    tradition: "Enochian",
    generic: true,
  },
  {
    id: "planetary_oracle",
    label: "Planetary Oracle",
    icon: "Globe",
    route: "/consult/planetary-oracle",
    category: "Ceremonial Oracle",
    mode: "generic_llm",
    description: "Agrippa-style planetary intelligence query",
    tradition: "Hermetic",
    generic: true,
  },

  // === Astronomical ===
  {
    id: "watch",
    label: "Astro Watch",
    icon: "Clock",
    route: "/consult/astro-watch",
    category: "Astronomical",
    mode: "astro_watch",
    description: "Live planetary hours, moon phase, houses, and sky map",
    tradition: "Hellenistic / Medieval",
    generic: false,
  },
  {
    id: "natal",
    label: "Natal Chart",
    icon: "Stars",
    route: "/consult/astrology",
    category: "Astronomical",
    mode: "astro_natal",
    description: "Full birth chart wheel with planets and houses",
    tradition: "Western astrology",
    generic: false,
  },
  {
    id: "horary",
    label: "Horary Astrology",
    icon: "Clock",
    route: "/consult/horary",
    category: "Astronomical",
    mode: "generic_llm",
    description: "Question chart read from the moment of asking",
    tradition: "William Lilly lineage",
    generic: true,
  },
  {
    id: "electional",
    label: "Electional Timing",
    icon: "Clock",
    route: "/consult/electional",
    category: "Astronomical",
    mode: "generic_llm",
    description: "Choose the perfect moment for a working or event",
    tradition: "Planetary magic",
    generic: true,
  },
  {
    id: "synastry",
    label: "Synastry / Compatibility",
    icon: "Heart",
    route: "/consult/synastry",
    category: "Astronomical",
    mode: "generic_llm",
    description: "Compare two charts for relationship dynamics and harmony",
    tradition: "Relationship astrology",
    generic: true,
  },
  {
    id: "vedic",
    label: "Vedic Jyotish",
    icon: "Stars",
    route: "/consult/vedic",
    category: "Astronomical",
    mode: "generic_llm",
    description: "Sidereal sign emphasis and dasha-style guidance",
    tradition: "Indian Jyotish",
    generic: true,
  },
  {
    id: "chinese_zodiac",
    label: "Chinese Zodiac",
    icon: "Star",
    route: "/consult/chinese-zodiac",
    category: "Astronomical",
    mode: "generic_llm",
    description: "Animal year, element balance, and four pillars overview",
    tradition: "Chinese metaphysics",
    generic: true,
  },

  // === Indian Traditions ===
  {
    id: "prashna",
    label: "Prashna Jyotish",
    icon: "Stars",
    route: "/consult/prashna",
    category: "Indian Traditions",
    mode: "generic_llm",
    description: "Horary chart for the moment of question — sidereal",
    tradition: "Indian Jyotish",
    generic: true,
  },
  {
    id: "panchang",
    label: "Panchanga Day Quality",
    icon: "Calendar",
    route: "/consult/panchang",
    category: "Indian Traditions",
    mode: "generic_llm",
    description: "Tithi, nakshatra, yoga, karana for today's quality",
    tradition: "Vedic calendar",
    generic: true,
  },
  {
    id: "ramayana_oracle",
    label: "Ramayana Verse Oracle",
    icon: "Book",
    route: "/consult/ramayana",
    category: "Indian Traditions",
    mode: "generic_llm",
    description: "Random shloka guidance with Sanskrit and English",
    tradition: "Hindu sacred text",
    generic: true,
  },
  {
    id: "mahabharata_lots",
    label: "Mahabharata Lots",
    icon: "Book",
    route: "/consult/mahabharata",
    category: "Indian Traditions",
    mode: "generic_llm",
    description: "Epic verse as oracle — original with translation",
    tradition: "Itihasa",
    generic: true,
  },
  {
    id: "tantra_yantra",
    label: "Yantra Meditation",
    icon: "Globe",
    route: "/consult/yantra",
    category: "Indian Traditions",
    mode: "generic_llm",
    description: "Contemplative yantra focus — non-operative guidance",
    tradition: "Tantric contemplative",
    generic: true,
  },
  {
    id: "ayurveda_dosha",
    label: "Ayurveda Dosha Read",
    icon: "Heart",
    route: "/consult/ayurveda-dosha",
    category: "Indian Traditions",
    mode: "generic_llm",
    description: "Constitutional hint from described traits — not medical",
    tradition: "Ayurveda",
    generic: true,
  },
  {
    id: "mantra_japa",
    label: "Mantra Japa Guidance",
    icon: "Music",
    route: "/consult/mantra-japa",
    category: "Indian Traditions",
    mode: "generic_llm",
    description: "Suggest traditional mantra with IAST and English",
    tradition: "Vedic / bhakti",
    generic: true,
  },

  // === Chinese Traditions ===
  {
    id: "bazi",
    label: "Bazi Four Pillars",
    icon: "Calendar",
    route: "/consult/bazi",
    category: "Chinese Traditions",
    mode: "generic_llm",
    description: "Year/month/day/hour pillars from birth data",
    tradition: "Chinese astrology",
    generic: true,
  },
  {
    id: "ziwei",
    label: "Zi Wei Dou Shu",
    icon: "Stars",
    route: "/consult/ziwei",
    category: "Chinese Traditions",
    mode: "generic_llm",
    description: "Purple Star astrology snapshot",
    tradition: "Chinese astrology",
    generic: true,
  },
  {
    id: "feng_shui",
    label: "Feng Shui Room Read",
    icon: "Home",
    route: "/consult/feng-shui",
    category: "Chinese Traditions",
    mode: "describe",
    description: "Describe room layout for qi flow guidance",
    tradition: "Feng shui",
    generic: true,
  },
  {
    id: "taoist_oracle",
    label: "Taoist Oracle",
    icon: "Scroll",
    route: "/consult/taoist-oracle",
    category: "Chinese Traditions",
    mode: "generic_llm",
    description: "Dao De Jing or Zhuangzi line as philosophical guidance",
    tradition: "Daoist philosophy",
    generic: true,
  },
  {
    id: "plum_blossom",
    label: "Plum Blossom Numerology",
    icon: "Calculator",
    route: "/consult/plum-blossom",
    category: "Chinese Traditions",
    mode: "generic_llm",
    description: "Meihua Yishu number oracle — Chinese numerology",
    tradition: "Chinese numerology",
    generic: true,
  },
  {
    id: "qimen",
    label: "Qi Men Dun Jia",
    icon: "Clock",
    route: "/consult/qimen",
    category: "Chinese Traditions",
    mode: "generic_llm",
    description: "Strategic timing oracle snapshot",
    tradition: "Chinese metaphysics",
    generic: true,
  },

  // === Japanese Traditions ===
  {
    id: "omikuji",
    label: "Omikuji Fortune",
    icon: "Scroll",
    route: "/consult/omikuji",
    category: "Japanese Traditions",
    mode: "generic_llm",
    description: "Shrine fortune slip — dai-kichi to kyo",
    tradition: "Shinto",
    generic: true,
  },
  {
    id: "renga",
    label: "Haiku Oracle",
    icon: "Feather",
    route: "/consult/haiku-oracle",
    category: "Japanese Traditions",
    mode: "generic_llm",
    description: "Poetic fragment as seasonal guidance and reflection",
    tradition: "Japanese poetry",
    generic: true,
  },
  {
    id: "kuji_kiri",
    label: "Kuji-kiri Contemplative",
    icon: "Hand",
    route: "/consult/kuji-kiri",
    category: "Japanese Traditions",
    mode: "generic_llm",
    description: "Nine hand-seals meditation context (curio — educational)",
    tradition: "Shugendo / ninjutsu folklore",
    generic: true,
  },
  {
    id: "reiki_guidance",
    label: "Reiki / Ki Flow",
    icon: "Sparkles",
    route: "/consult/reiki",
    category: "Japanese Traditions",
    mode: "generic_llm",
    description: "Energy balance meditation and guidance",
    tradition: "Japanese ki work",
    generic: true,
  },
  {
    id: "yokai_omen",
    label: "Yokai Folk Omen",
    icon: "Moon",
    route: "/consult/yokai",
    category: "Japanese Traditions",
    mode: "generic_llm",
    description: "Japanese folklore sign reading — entertainment",
    tradition: "Japanese folk",
    generic: true,
  },

  // === Meditation & Relaxation ===
  {
    id: "pranayama",
    label: "Pranayama Session",
    icon: "Wind",
    route: "/consult/pranayama",
    category: "Meditation & Relaxation",
    mode: "generic_llm",
    description: "Guided Indian breath practice with Sanskrit names",
    tradition: "Yoga",
    generic: true,
  },
  {
    id: "yoga_nidra_guide",
    label: "Yoga Nidra Script",
    icon: "Moon",
    route: "/consult/yoga-nidra",
    category: "Meditation & Relaxation",
    mode: "generic_llm",
    description: "Body rotation relaxation with sankalpa",
    tradition: "Tantric yoga",
    generic: true,
  },
  {
    id: "qigong_session",
    label: "Qigong Flow",
    icon: "Wind",
    route: "/consult/qigong",
    category: "Meditation & Relaxation",
    mode: "generic_llm",
    description: "Eight Brocades or standing meditation — Chinese terms",
    tradition: "Qigong",
    generic: true,
  },
  {
    id: "zazen_guide",
    label: "Zazen Sitting Guide",
    icon: "Moon",
    route: "/consult/zazen",
    category: "Meditation & Relaxation",
    mode: "generic_llm",
    description: "Shikantaza instructions — Japanese and English",
    tradition: "Zen",
    generic: true,
  },
  {
    id: "nembutsu_guide",
    label: "Nembutsu Chant Guide",
    icon: "Music",
    route: "/consult/nembutsu",
    category: "Meditation & Relaxation",
    mode: "generic_llm",
    description: "Namu Amida Butsu practice with kanji",
    tradition: "Pure Land",
    generic: true,
  },
  {
    id: "body_scan",
    label: "Progressive Relaxation",
    icon: "Heart",
    route: "/consult/body-scan",
    category: "Meditation & Relaxation",
    mode: "generic_llm",
    description: "Full body scan — East-West blended approach",
    tradition: "Universal",
    generic: true,
  },
  {
    id: "sound_bath",
    label: "Mantra / Sound Bath",
    icon: "Music",
    route: "/consult/sound-bath",
    category: "Meditation & Relaxation",
    mode: "generic_llm",
    description: "Seed syllables (om, ah, hum) with translation",
    tradition: "Indo-Tibetan-Chinese",
    generic: true,
  },
];

/** Systems that need custom page components (not generic). */
export const SPECIALIZED_SYSTEMS = DIVINATION_SYSTEMS.filter((s) => !s.generic);

/** Systems that can use GenericDivinationPage. */
export const GENERIC_SYSTEMS = DIVINATION_SYSTEMS.filter((s) => s.generic);

/** Categorize systems for the ConsultPage grid. */
export function getSystemsByCategory() {
  const map = new Map<string, DivinationSystemDef[]>();
  for (const sys of DIVINATION_SYSTEMS) {
    const existing = map.get(sys.category) ?? [];
    existing.push(sys);
    map.set(sys.category, existing);
  }
  return map;
}

/** Lookup a system by its id. */
export function getSystemById(id: string): DivinationSystemDef | undefined {
  return DIVINATION_SYSTEMS.find((s) => s.id === id);
}

/** Lookup a system by its route path. */
export function getSystemByRoute(route: string): DivinationSystemDef | undefined {
  return DIVINATION_SYSTEMS.find((s) => s.route === route);
}
