export interface Hexagram {
  number: number;
  name: string;
  chinese: string;
  english: string;
  binary: string;
  judgment: string;
  image: string;
  keywords: string[];
}

export const HEXAGRAMS: Hexagram[] = [
  { number: 1, name: "Qián", chinese: "乾", english: "The Creative", binary: "111111", judgment: "Supreme success. Perseverance furthers.", image: "The movement of heaven is full of power. The superior person makes himself strong and untiring.", keywords: ["creativity", "strength", "heaven", "initiative", "leadership", "power"] },
  { number: 2, name: "Kūn", chinese: "坤", english: "The Receptive", binary: "000000", judgment: "Supreme success. Perseverance of the mare brings good fortune.", image: "The condition of earth, receptive devotion. The superior person carries the outer world with breadth and strength.", keywords: ["receptivity", "devotion", "earth", "nurturing", "endurance", "yield"] },
  { number: 3, name: "Zhūn", chinese: "屯", english: "Initial Difficulty", binary: "100010", judgment: "Initial difficulty. Perseverance furthers. It is favorable to appoint helpers.", image: "Clouds and thunder. The superior person brings order out of chaos.", keywords: ["beginning", "difficulty", "birth", "struggle", "potential", "chaos"] },
  { number: 4, name: "Méng", chinese: "蒙", english: "Youthful Folly", binary: "010001", judgment: "Youthful folly has success. The young fool seeks me, not I who seeks the young fool.", image: "A spring bursts from the mountain. The superior person fosters character by thoroughness in all deeds.", keywords: ["youth", "inexperience", "learning", "innocence", "guidance", "growth"] },
  { number: 5, name: "Xū", chinese: "需", english: "Waiting", binary: "010111", judgment: "Waiting. If you are sincere, you have light and success. Perseverance brings good fortune.", image: "Clouds rising up to heaven. The superior person eats and drinks and is joyous.", keywords: ["patience", "waiting", "timing", "preparation", "trust", "nourishment"] },
  { number: 6, name: "Sòng", chinese: "讼", english: "Conflict", binary: "111010", judgment: "Conflict. You are sincere and obstructed. Careful halfway brings good fortune.", image: "Heaven and water going contrary. The superior person plans before taking action.", keywords: ["conflict", "dispute", "tension", "opposition", "justice", "strategy"] },
  { number: 7, name: "Shī", chinese: "师", english: "The Army", binary: "010000", judgment: "The army needs perseverance and a strong leader. Good fortune without blame.", image: "Water in the earth. The superior person nourishes the people with virtue.", keywords: ["army", "discipline", "leadership", "organization", "collective", "order"] },
  { number: 8, name: "Bǐ", chinese: "比", english: "Holding Together", binary: "000010", judgment: "Holding together brings good fortune. The king approaches his vassals.", image: "Water over earth. The former kings established relationships and loved all beings.", keywords: ["unity", "alliance", "companionship", "harmony", "loyalty", "support"] },
  { number: 9, name: "Xiǎo Chù", chinese: "小畜", english: "Small Tames", binary: "111011", judgment: "The small tames. Success. Dense clouds, no rain from the western border.", image: "Wind moving above heaven. The superior person refines the outer self through inner virtue.", keywords: ["restraint", "gentle", "accumulation", "patience", "refinement", "subtle"] },
  { number: 10, name: "Lǚ", chinese: "履", english: "Treading", binary: "110111", judgment: "Treading on the tail of a tiger. It does not bite. Success.", image: "Heaven above, lake below. The superior person distinguishes high and low and sets the people's will at rest.", keywords: ["caution", "conduct", "walking", "danger", "grace", "propriety"] },
  { number: 11, name: "Tài", chinese: "泰", english: "Peace", binary: "000111", judgment: "Peace. The small departs, the great approaches. Good fortune.", image: "Heaven and earth unite. The ruler adapts to the times and fosters harmony.", keywords: ["peace", "harmony", "prosperity", "union", "balance", "flow"] },
  { number: 12, name: "Pǐ", chinese: "否", english: "Standstill", binary: "111000", judgment: "Standstill. Evil people do not further. The superior person withdraws.", image: "Heaven and earth separated. The superior person withdraws to cultivate inner virtue.", keywords: ["stagnation", "blockage", "withdrawal", "decay", "isolation", "patience"] },
  { number: 13, name: "Tóng Rén", chinese: "同人", english: "Fellowship", binary: "101111", judgment: "Fellowship in the open. Success. Perseverance furthers.", image: "Heaven with fire. The superior person distinguishes things according to their kinds.", keywords: ["community", "fellowship", "harmony", "connection", "shared purpose", "openness"] },
  { number: 14, name: "Dà Yǒu", chinese: "大有", english: "Great Possession", binary: "111101", judgment: "Supreme success. Abundance and prosperity through humility.", image: "Fire over heaven. The superior person curbs evil and promotes good.", keywords: ["abundance", "wealth", "success", "generosity", "enlightenment", "prosperity"] },
  { number: 15, name: "Qiān", chinese: "谦", english: "Modesty", binary: "001000", judgment: "Modesty brings success. The superior person carries matters through.", image: "Mountain within earth. The superior person reduces what is too much and increases what is too little.", keywords: ["humility", "modesty", "balance", "simplicity", "groundedness", "wisdom"] },
  { number: 16, name: "Yù", chinese: "豫", english: "Enthusiasm", binary: "000100", judgment: "Enthusiasm. It furthers to install helpers and set armies marching.", image: "Thunder coming from earth. The ancient kings composed music to honor virtue.", keywords: ["enthusiasm", "joy", "inspiration", "movement", "celebration", "energy"] },
  { number: 17, name: "Suí", chinese: "随", english: "Following", binary: "100110", judgment: "Following has supreme success. Perseverance furthers. No blame.", image: "Thunder within the lake. The superior person rests in the evening and reflects.", keywords: ["adaptability", "following", "accord", "flexibility", "timing", "surrender"] },
  { number: 18, name: "Gǔ", chinese: "蛊", english: "Work on Decay", binary: "011001", judgment: "Work on what has been spoiled has supreme success. The crossing of great water.", image: "Wind below mountain. The superior person nourishes the people and awakens the mind.", keywords: ["decay", "restoration", "repair", "transformation", "corruption", "healing"] },
  { number: 19, name: "Lín", chinese: "临", english: "Approach", binary: "000011", judgment: "Approach has supreme success. Perseverance furthers.", image: "Earth above lake. The superior person teaches and thinks boundlessly.", keywords: ["approach", "advance", "growth", "opportunity", "leadership", "influence"] },
  { number: 20, name: "Guān", chinese: "观", english: "Contemplation", binary: "110000", judgment: "Contemplation. The ablution has been made. When the truth is known, all is well.", image: "Wind over earth. The ancient kings observed and created order.", keywords: ["observation", "contemplation", "insight", "perspective", "wisdom", "reflection"] },
  { number: 21, name: "Shì Kè", chinese: "噬嗑", english: "Biting Through", binary: "100101", judgment: "Biting through has success. It is favorable to use legal measures.", image: "Thunder and lightning. The superior person clarifies laws and judgments.", keywords: ["justice", "breakthrough", "obstacle", "resolution", "confrontation", "truth"] },
  { number: 22, name: "Bì", chinese: "贲", english: "Grace", binary: "101001", judgment: "Grace has success. Small matters are favorable.", image: "Fire at the foot of the mountain. The superior person governs without harshness.", keywords: ["beauty", "grace", "adornment", "refinement", "elegance", "surface"] },
  { number: 23, name: "Bō", chinese: "剥", english: "Splitting Apart", binary: "000001", judgment: "Splitting apart. It does not further to go anywhere.", image: "Mountain resting on earth. The superior person supports the weak below.", keywords: ["decay", "collapse", "erosion", "separation", "decline", "shedding"] },
  { number: 24, name: "Fù", chinese: "复", english: "Return", binary: "100000", judgment: "Return. Success. No misfortune. The ancient way of renewal.", image: "Thunder within earth. The superior person closes the gate on error.", keywords: ["return", "renewal", "rebirth", "cycle", "restoration", "repetition"] },
  { number: 25, name: "Wú Wàng", chinese: "无妄", english: "Innocence", binary: "111001", judgment: "Innocence. Supreme success. Perseverance furthers. If not genuine, misfortune.", image: "Thunder under heaven. The superior person fosters vitality and lives in harmony.", keywords: ["innocence", "spontaneity", "purity", "naturalness", "sincerity", "simplicity"] },
  { number: 26, name: "Dà Chù", chinese: "大畜", english: "Great Tames", binary: "100111", judgment: "The great tames. Perseverance furthers. Not eating at home brings good fortune.", image: "Heaven within mountain. The superior person learns and stores up knowledge.", keywords: ["restraint", "accumulation", "discipline", "preparation", "power", "potential"] },
  { number: 27, name: "Yí", chinese: "颐", english: "Nourishment", binary: "100001", judgment: "Nourishment. Perseverance brings good fortune. Watch the mouth.", image: "Thunder under mountain. The superior person speaks with care and eats with moderation.", keywords: ["nourishment", "sustenance", "care", "balance", "health", "moderation"] },
  { number: 28, name: "Dà Guò", chinese: "大过", english: "Great Excess", binary: "110011", judgment: "The ridgepole sags. It furthers to have somewhere to go.", image: "Lake flooding tree. The superior person stands alone and is unafraid.", keywords: ["excess", "overwhelm", "crisis", "extremity", "pressure", "transition"] },
  { number: 29, name: "Kǎn", chinese: "坎", english: "The Abysmal", binary: "010010", judgment: "The abysmal repeated. Sincerity brings success.", image: "Water flowing continuously. The superior person acts with sincerity and clarity.", keywords: ["danger", "depth", "challenge", "risk", "courage", "perseverance"] },
  { number: 30, name: "Lí", chinese: "离", english: "The Clinging", binary: "101101", judgment: "The clinging. Perseverance brings success. Cultivate clarity.", image: "Brightness doubled. The superior person cultivates clarity and illuminates the world.", keywords: ["clarity", "illumination", "attachment", "awareness", "light", "consciousness"] },
  { number: 31, name: "Xián", chinese: "咸", english: "Influence", binary: "001110", judgment: "Influence. Success. Perseverance furthers. Taking a maiden brings good fortune.", image: "Lake over mountain. The superior person receives others with humility.", keywords: ["attraction", "influence", "connection", "emotion", "receptivity", "union"] },
  { number: 32, name: "Héng", chinese: "恒", english: "Duration", binary: "011100", judgment: "Duration. Success. No blame. Perseverance furthers.", image: "Thunder and wind. The superior person stands firm without changing direction.", keywords: ["endurance", "stability", "persistence", "commitment", "lasting", "constancy"] },
  { number: 33, name: "Dùn", chinese: "遁", english: "Retreat", binary: "111100", judgment: "Retreat. Success in small matters. Perseverance furthers.", image: "Mountain under heaven. The superior person keeps the inferior at a distance.", keywords: ["withdrawal", "retreat", "timing", "strategy", "patience", "preservation"] },
  { number: 34, name: "Dà Zhuàng", chinese: "大壮", english: "Great Power", binary: "001111", judgment: "Great power. Perseverance furthers. The ram butts against a fence.", image: "Thunder above heaven. The superior person does not tread where there is no path.", keywords: ["strength", "power", "assertion", "vitality", "momentum", "caution"] },
  { number: 35, name: "Jìn", chinese: "晋", english: "Progress", binary: "101000", judgment: "Progress. The powerful horse is granted. The king receives him.", image: "Fire rising above earth. The superior person brightens virtue and shines.", keywords: ["advancement", "progress", "growth", "success", "recognition", "rise"] },
  { number: 36, name: "Míng Yí", chinese: "明夷", english: "Darkening of Light", binary: "000101", judgment: "Darkening of the light. Perseverance in adversity furthers.", image: "Light hidden under earth. The superior person remains humble while inwardly bright.", keywords: ["darkness", "obscurity", "adversity", "hiding", "wisdom", "endurance"] },
  { number: 37, name: "Jiā Rén", chinese: "家人", english: "The Family", binary: "101011", judgment: "The family. Perseverance furthers for the woman.", image: "Wind from fire. The superior person speaks with substance and acts consistently.", keywords: ["family", "home", "belonging", "harmony", "roots", "tradition"] },
  { number: 38, name: "Kuí", chinese: "睽", english: "Opposition", binary: "110101", judgment: "Opposition. Small matters are favorable.", image: "Fire above lake. The superior person finds common ground in differences.", keywords: ["opposition", "division", "difference", "conflict", "reconciliation", "tension"] },
  { number: 39, name: "Jiǎn", chinese: "蹇", english: "Obstruction", binary: "010100", judgment: "Obstruction. The southwest is favorable. The northeast is unfavorable.", image: "Water above mountain. The superior person turns inward to cultivate character.", keywords: ["obstacle", "difficulty", "blockage", "caution", "perseverance", "retreat"] },
  { number: 40, name: "Xiè", chinese: "解", english: "Deliverance", binary: "001010", judgment: "Deliverance. The southwest is favorable. Return brings good fortune.", image: "Thunder and rain. The superior person forgives errors and pardons mistakes.", keywords: ["release", "freedom", "resolution", "relief", "forgiveness", "deliverance"] },
  { number: 41, name: "Sǔn", chinese: "损", english: "Decrease", binary: "110001", judgment: "Decrease combined with sincerity brings supreme success. Be frugal.", image: "Lake below mountain. The superior person controls anger and restrains desires.", keywords: ["loss", "decrease", "simplify", "sacrifice", "letting go", "frugality"] },
  { number: 42, name: "Yì", chinese: "益", english: "Increase", binary: "100011", judgment: "Increase. It furthers to undertake something. The crossing of great water.", image: "Wind and thunder. The superior person promotes good and helps others.", keywords: ["gain", "growth", "abundance", "benefit", "expansion", "blessing"] },
  { number: 43, name: "Guài", chinese: "夬", english: "Breakthrough", binary: "111110", judgment: "Breakthrough. The royal approach. Be sincere and resolute.", image: "Lake rising to heaven. The superior person distributes wealth and lets virtue shine.", keywords: ["decision", "breakthrough", "resolution", "action", "courage", "clarity"] },
  { number: 44, name: "Gòu", chinese: "姤", english: "Coming to Meet", binary: "011111", judgment: "Coming to meet. The maiden is powerful. Do not marry such a maiden.", image: "Wind under heaven. The ruler issues commands and spreads them far.", keywords: ["encounter", "meeting", "opportunity", "surprise", "connection", "caution"] },
  { number: 45, name: "Cuì", chinese: "萃", english: "Gathering Together", binary: "000110", judgment: "Gathering together. Success. The king approaches his temple.", image: "Lake over earth. The superior person prepares for gatherings and trains for war.", keywords: ["gathering", "community", "convergence", "unity", "collective", "purpose"] },
  { number: 46, name: "Shēng", chinese: "升", english: "Pushing Upward", binary: "011000", judgment: "Pushing upward has supreme success. See the great person. Do not worry.", image: "Wood growing from earth. The superior person accumulates virtue and builds character.", keywords: ["ascent", "growth", "progress", "promotion", "development", "rise"] },
  { number: 47, name: "Kùn", chinese: "困", english: "Oppression", binary: "010110", judgment: "Oppression. Success. Perseverance brings good fortune.", image: "Lake without water. The superior person sacrifices life to fulfill will.", keywords: ["exhaustion", "oppression", "hardship", "limitation", "endurance", "perseverance"] },
  { number: 48, name: "Jǐng", chinese: "井", english: "The Well", binary: "011010", judgment: "The well. The town may change but the well stays. No blame.", image: "Wood above water. The superior person encourages the people and urges mutual support.", keywords: ["source", "foundation", "nourishment", "stability", "community", "sustenance"] },
  { number: 49, name: "Gé", chinese: "革", english: "Revolution", binary: "101110", judgment: "Revolution. When the truth is clear, great success.", image: "Fire in the lake. The superior person regulates the calendar and clarifies seasons.", keywords: ["change", "revolution", "transformation", "reform", "upheaval", "renewal"] },
  { number: 50, name: "Dǐng", chinese: "鼎", english: "The Cauldron", binary: "011101", judgment: "The cauldron. Supreme good fortune. Success.", image: "Fire over wood. The superior person consolidates fate and clarifies destiny.", keywords: ["nourishment", "transformation", "alchemy", "refinement", "civilization", "sacred"] },
  { number: 51, name: "Zhèn", chinese: "震", english: "The Arousing", binary: "001001", judgment: "The arousing brings success. Thunder comes and all is calm.", image: "Thunder repeated. The superior person examines life and corrects faults.", keywords: ["shock", "awakening", "initiation", "movement", "crisis", "transformation"] },
  { number: 52, name: "Gèn", chinese: "艮", english: "The Stillness", binary: "100100", judgment: "Stillness. Keeping the back still. Not sensing the body leads to peace.", image: "Mountain doubled. The superior person does not let thoughts wander beyond their station.", keywords: ["stillness", "meditation", "rest", "calm", "boundary", "peace"] },
  { number: 53, name: "Jiàn", chinese: "渐", english: "Development", binary: "110100", judgment: "Development. The maiden is given in marriage. Good fortune.", image: "Wood on mountain. The superior person dwells in virtue and improves custom.", keywords: ["gradual", "progress", "development", "growth", "patience", "unfolding"] },
  { number: 54, name: "Guī Mèi", chinese: "归妹", english: "The Marrying Maiden", binary: "001101", judgment: "The marrying maiden. Undertaking brings misfortune. Nothing furthers.", image: "Thunder over lake. The superior person sees the end and knows limitations.", keywords: ["union", "attachment", "dependence", "transition", "partnership", "caution"] },
  { number: 55, name: "Fēng", chinese: "丰", english: "Abundance", binary: "101100", judgment: "Abundance has success. The king achieves abundance. The sun at midday.", image: "Thunder and lightning. The superior person judges cases and applies punishments.", keywords: ["abundance", "fullness", "prosperity", "peak", "fulfillment", "generosity"] },
  { number: 56, name: "Lǚ", chinese: "旅", english: "The Wanderer", binary: "001011", judgment: "The wanderer. Success through smallness. Perseverance brings good fortune.", image: "Fire on mountain. The superior person is clear and prudent in judgment.", keywords: ["travel", "wandering", "journey", "transience", "adaptation", "exploration"] },
  { number: 57, name: "Xùn", chinese: "巽", english: "The Gentle", binary: "011011", judgment: "The gentle. Success through smallness. It furthers to have somewhere to go.", image: "Wind following wind. The superior person spreads commands and carries out affairs.", keywords: ["gentleness", "penetration", "adaptability", "influence", "persuasion", "flexibility"] },
  { number: 58, name: "Duì", chinese: "兑", english: "The Joyous", binary: "110110", judgment: "The joyous. Success. Perseverance furthers.", image: "Lakes over lake. The superior person discusses and shares wisdom with friends.", keywords: ["joy", "pleasure", "communication", "connection", "openness", "happiness"] },
  { number: 59, name: "Huàn", chinese: "涣", english: "Dispersion", binary: "010011", judgment: "Dispersion. Success. The king approaches his temple.", image: "Wind over water. The ancient kings offered to the creator and established temples.", keywords: ["dispersal", "release", "scattering", "dissolution", "renewal", "clarity"] },
  { number: 60, name: "Jié", chinese: "节", english: "Limitation", binary: "110010", judgment: "Limitation. Success. Bitter limitation should not be persevered in.", image: "Water over lake. The superior person creates standards and measures virtue.", keywords: ["limits", "boundaries", "moderation", "discipline", "structure", "restraint"] },
  { number: 61, name: "Zhōng Fú", chinese: "中孚", english: "Inner Truth", binary: "011110", judgment: "Inner truth. Pigs and fishes. good fortune. The crossing of great water.", image: "Wind over lake. The superior person deliberates and pardons with compassion.", keywords: ["truth", "sincerity", "integrity", "trust", "authenticity", "heart"] },
  { number: 62, name: "Xiǎo Guò", chinese: "小过", english: "Small Excess", binary: "001100", judgment: "Small excess. Success. Perseverance brings good fortune. Small things are possible.", image: "Thunder on mountain. The superior person is humble in conduct and mourns with restraint.", keywords: ["minor excess", "caution", "moderation", "humility", "detail", "precision"] },
  { number: 63, name: "Jì Jì", chinese: "既济", english: "After Completion", binary: "010101", judgment: "After completion. Success in small matters. Perseverance furthers from beginning to end.", image: "Water over fire. The superior person anticipates danger and takes precautions.", keywords: ["completion", "fulfillment", "accomplishment", "transition", "caution", "balance"] },
  { number: 64, name: "Wèi Jì", chinese: "未济", english: "Before Completion", binary: "101010", judgment: "Before completion. Success. The fox crosses the stream. No blame.", image: "Fire over water. The superior person discerns and protects against disorder.", keywords: ["incompletion", "transition", "potential", "caution", "forward motion", "uncertainty"] },
];

export function getHexagramByNumber(n: number): Hexagram | undefined {
  return HEXAGRAMS.find((h) => h.number === n);
}

export function getHexagramByBinary(binary: string): Hexagram | undefined {
  return HEXAGRAMS.find((h) => h.binary === binary);
}

export function linesToBinary(lines: number[]): string {
  return lines.map((l) => (l % 2 === 0 ? "0" : "1")).join("");
}

export function coinValuesToLine(v1: number, v2: number, v3: number): { value: number; type: string; yin: boolean } {
  const total = v1 + v2 + v3;
  if (total === 6) return { value: 6, type: "old yin", yin: true };
  if (total === 7) return { value: 7, type: "young yang", yin: false };
  if (total === 8) return { value: 8, type: "young yin", yin: true };
  return { value: 9, type: "old yang", yin: false };
}
